cpu: Only compile runstate_is_running() for system mode
When compiling QEMU for user mode, the following error occurs:

/usr/bin/ld: libcommon.fa.p/hw_core_cpu-common.c.o: in function `cpu_common_realizefn':
/qemu-7.2.0/build/../hw/core/cpu-common.c:212: undefined reference to `runstate_is_running'

VM runstates are only available in system mode; they are not available in user
mode. Since CONFIG_USER_ONLY isn't available to cpu-common.c, move the check to
cpu.c and add a compiler directive.

Fixes:
6c17d5878a14 ("cpus: resume hotplugged vCPU only when the guest is running")

JIRA: https://jira.oci.oraclecorp.com/browse/LINUX-16325

Signed-off-by: Mark Kanda <mark.kanda@oracle.com>
Reviewed-by: Dongli Zhang <dongli.zhang@oracle.com>