error: define g_autoptr() cleanup function for the Error type
Automatic memory management helps avoid memory safety issues.

Reviewed-by: Peter Xu <peterx@redhat.com>
Link: https://lore.kernel.org/qemu-devel/a5843c5fa64d7e5239a4316092ec0ef0d10c2320.1741124640.git.maciej.szmigiero@oracle.com
Signed-off-by: Cédric Le Goater <clg@redhat.com>
(cherry picked from commit 18eb55546a54e443d94a4c49286348176ad4b00a)

JIRA: https://jira.oci.oraclecorp.com/browse/LINUX-15752

Reviewed-by: Liam Merwick <liam.merwick@oracle.com>
Signed-off-by: Maciej S. Szmigiero <maciej.szmigiero@oracle.com>