spec: disable keyutils
QEMU fails to build with keyutils-libs-1.5.10-9.0.1 due to missing symbols:

libcommon.fa.p/backends_cryptodev-lkcf.c.o: In function `cryptodev_lkcf_execute_task':
backends/cryptodev-lkcf.c:358: undefined reference to `keyctl_pkey_encrypt'
backends/cryptodev-lkcf.c:370: undefined reference to `keyctl_pkey_decrypt'
backends/cryptodev-lkcf.c:382: undefined reference to `keyctl_pkey_sign'
backends/cryptodev-lkcf.c:394: undefined reference to `keyctl_pkey_verify'

We don't need keyutils so disable it as a workaround.

Orabug: 36903731

Signed-off-by: Mark Kanda <mark.kanda@oracle.com>
Reviewed-by: Karl Heubaum <karl.heubaum@oracle.com>