migration: Fix build warning from missing header
When building with rpmbuild, Jenkins logs this warning:

../migration/page_cache.c: In function 'isal_sha256_symbols_available':
../migration/page_cache.c:483:9: warning: implicit declaration of function 'error_report'; did you mean 'error_report_err'? [-Wimplicit-function-declaration]
         error_report("Could not dlopen library %s", ISAL_LIB_FILE_NAME);
         ^~~~~~~~~~~~
         error_report_err

Fix by adding the header.

Orabug: 38732433

Signed-off-by: Elena Ufimtseva <elena.ufimtseva@oracle.com>
Reviewed-by: Karl Heubaum <karl.heubaum@oracle.com>